export default courses = [
  {
    image: require('../src/assets/images/banners/1.jpg'),
    id: '63cfbb959dae2ef89dc104c5',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'JavaScript Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/2.jpg'),
    id: '63cfbb959dae2ef89dc104c6',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'JavaScript Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Punjab, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/3.jpg'),
    id: '63cfbb959dae2ef89dc104c7',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'Python For Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/4.jpg'),
    id: '63cfbb959dae2ef89dc104c8',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'Python For Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/1.jpg'),
    id: '63cfbb959dae2ef89dc104c11',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'Python For Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/2.jpg'),
    id: '63cfbb959dae2ef89dc104c12',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'JavaScript Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Punjab, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/3.jpg'),
    id: '63cfbb959dae2ef89dc104c13',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'Python For Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
  {
    image: require('../src/assets/images/banners/4.jpg'),
    id: '63cfbb959dae2ef89dc104c14',
    images: [
      require('../src/assets/images/banners/1.jpg'),
      require('../src/assets/images/banners/2.jpg'),
      require('../src/assets/images/banners/3.jpg'),
    ],
    name: 'Python For Beginers',
    ratings: 4.4,
    reviews: 200,
    category: 'Delhi, India',
    price: 3000,
    mrp: 5000,
  },
];
