export default Hotels = [
  {
    image: require('../src/assets/images/hotels/1.jpg'),
    id: '63cfbb959dae2ef89dc104c5',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/2.jpg'),
    id: '63cfbb959dae2ef89dc104c6',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'My Girlfriend Hotel',
    ratings: 4.4,
    reviews: 200,
    address: 'Punjab, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/3.jpg'),
    id: '63cfbb959dae2ef89dc104c7',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/4.jpg'),
    id: '63cfbb959dae2ef89dc104c8',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/1.jpg'),
    id: '63cfbb959dae2ef89dc104c11',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/2.jpg'),
    id: '63cfbb959dae2ef89dc104c12',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'My Girlfriend Hotel',
    ratings: 4.4,
    reviews: 200,
    address: 'Punjab, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/3.jpg'),
    id: '63cfbb959dae2ef89dc104c13',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
  {
    image: require('../src/assets/images/hotels/4.jpg'),
    id: '63cfbb959dae2ef89dc104c14',
    images: [
      require('../src/assets/images/hotels/1.jpg'),
      require('../src/assets/images/hotels/2.jpg'),
      require('../src/assets/images/hotels/3.jpg'),
    ],
    name: 'Second Hand Wife',
    ratings: 4.4,
    reviews: 200,
    address: 'Delhi, India',
    price: 3000,
  },
];
